# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalogdb:
     image : mongo
  basketdb:
     image: redis

  CreditService:
    image: tsin24/CreditService
    build:
      context: .
      dockerfile: src/CreditService/Dockerfile
  AccountService:
    image: tsin24/basketapi
    build:
      context: .
      dockerfile: src/AccountService/Dockerfile
volumes: 
    mongo_data: 
   
