# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  voiceassistdb:
     image : mongo
  voiceassistcache:
     image: redis

  CreditCardService:
    image: tsin24/CreditCardService
    build:
      context: .
      dockerfile: src/CreditCardService/Dockerfile
  AccountService:
    image: tsin24/AccountService
    build:
      context: .
      dockerfile: src/AccountService/Dockerfile
  UserService:
    image: tsin24/UserService
    build:
      context: .
      dockerfile: src/UserService/Dockerfile
volumes: 
    mongo_data: 
   
