version: '3.4'

services: 
    voiceassistdb:
      image: mongo
      container_name: voiceassistdb
      restart: always
      volumes:  
         - mongo_data:/data/db
      ports:
         - "27017:27017"
    voiceassistcache:
      image: redis
      container_name: voiceassistcache
      restart: always
      ports:
         - "6379:6379"     

    creditcardservice:
      image: tsin24/creditcardservice
      environment: 
          - ASPNETCORE_ENVIRONMENT=Development
          - "CreditDatabaseSettings:ConnectionString=mongodb://voiceassistdb:27017"
      depends_on: 
          - voiceassistdb
      ports: 
          -  "8001:80"
    accountservice:
      image: tsin24/accountservice
      environment: 
          - ASPNETCORE_ENVIRONMENT=Development
         - "AccountDatabaseSettings:ConnectionString=mongodb://voiceassistdb:27017"
      depends_on: 
          - voiceassistdb
      ports: 
          -  "8002:80"    
    userservice:
      image: tsin24/userservice
      environment: 
          - ASPNETCORE_ENVIRONMENT=Development
          - "ConnectionString:Redis=voiceassistcache:6379"
      depends_on: 
          - voiceassistcache
      ports: 
          -  "8003:80"   
volumes: 
    mongo_data:                     